name: unidthon
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  buttons_tabbar: ^1.3.8
  flutter_platform_alert: ^0.4.0
  flutter_dash: ^1.0.0
  dotted_border: ^2.1.0
  flutter_flip_card: ^0.0.4
  pretty_qr_code: ^3.0.0
  shimmer: ^3.0.0
  http: ^1.1.0
  qr_code_scanner: ^1.0.1
  lottie: ^2.7.0
  kakao_flutter_sdk: ^1.6.1

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logindone.json
    - assets/applogo1.png
    - assets/profile_example.jpeg
    - assets/kakao_login.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 100
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 200
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 300
        - asset: assets/fonts/Inter-Extralight.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 500
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 600
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 900
